create table class_details (id  bigserial not null, end_time time, start_time time, type varchar(255), class_object_id int8 not null, grouped_daily_schedule_id int8 not null, lecturer_id int8 not null, primary key (id));
create table class_objects (id  bigserial not null, name varchar(255), short_name varchar(255), primary key (id));
create table grouped_daily_schedules (id  bigserial not null, date date, group_id int8, schedule_id int8 not null, primary key (id));
create table lecturers (id  bigserial not null, email varchar(255), name varchar(255), shortname varchar(255), surname varchar(255), primary key (id));
create table schedule_versions (id  bigserial not null, addition_date timestamp, update_date timestamp, url varchar(255), primary key (id));
create table schedules (id  bigserial not null, is_latest boolean, version_id int8 not null, primary key (id));
alter table lecturers add constraint UK2vuuglltdcfcelhmim28anfxg unique (id, name, surname, shortname);
alter table schedule_versions add constraint UK2h63d1wh0f76oqpn0tw28ks3e unique (id, url, addition_date);
alter table class_details add constraint FKseu1wgueaq1rno1oq30vy2o0k foreign key (class_object_id) references class_objects;
alter table class_details add constraint FK88hr7wxi9qf0jdm616ri9u2p7 foreign key (grouped_daily_schedule_id) references grouped_daily_schedules;
alter table class_details add constraint FKegnsk18mm44icd5y9xqbpc2ls foreign key (lecturer_id) references lecturers;
alter table grouped_daily_schedules add constraint FK4hiq0yykoxa3altxwv6vjxrc0 foreign key (schedule_id) references schedules;
alter table schedules add constraint FK6so6gg36a0qgs0yrruetv28wl foreign key (version_id) references schedule_versions;
